### ISSUE TITLE
lev_distance seems to incorrectly allow transpositions.

### ISSUE THREAD

**Issue by srdeaton** [lewinfox/levitate#13] opened 2024-03-08 01:32 UTC
I was using lev_distance and found that lev_disance('01','10') = 1 which is false, it's 1. Unless transpositions are allowed, which does not make this edit distance Levenshtein. Allowing transpositions is nice for applications like genetics, but I need the version without transpositions. Having options to pick and choose which edit possibilities the metric can use would be very nice.
 I might be missing something, but this seems to be the case.
thanks,
Shaun

**Comment by srdeaton** [comment] 2024-03-08 01:41
Sorry, typo. Supposed to get  lev_disance('01','10') = 2, not 1.

**Comment by lewinfox** [comment] 2024-03-08 02:13
Thanks, I’ll take a look at it as soon as I have some time. Distance
calculations are handled by ‘stringdist::stringdistmatrix()’ under the hood
- if you get a chance could you see what output that gives? Will help me
narrow down the cause. If it turns out to be something stringdist can
switch on and off, you can pass the relevant argument to ‘…’ and it will be
passed down to stringdist.

**Comment by lewinfox** [comment] 2024-03-08 04:03
Answering my own question here

``` r
stringdist::stringdist("01", "10")
#> 1

levitate::lev_distance("01", "10")
#> 1
```

Reading `help(stringdist::stringdist)` points us towards the `method` argument. Stringdist uses `method = "osa"` by default, which (I assume) allows transpositions. Setting `method = "lv"` seems to do what you want. See [`help(stringdist-metrics)`](https://rdrr.io/cran/stringdist/man/stringdist-metrics.html) for other options. 
``` r
levitate::lev_distance("01", "10", method="lv")
#> 2
```

I have to say this is counter to my own intuition about how the package works, so thank you for raising it. 

I'm not inclined to change the default method now that the package is being used in the wild, and the [documentation](https://www.lewinfox.com/levitate/reference/lev_distance.html) does say that the work is delegated to `stringdist` and sets out how to pass your own options. I think it's probably worth calling this out more clearly in the docs, so I'll open an issue for that.

**Comment by lewinfox** [comment] 2024-03-08 04:05
Docs task added in #14 - closing.

**Closed as completed by lewinfox** 2024-03-08 04:05 UTC

**Comment by lewinfox** [comment] 2024-03-08 04:07
@srdeaton just want to add, this is particularly counter-intuitive given the name of the package 🤦‍♂️ Bit of an oversight on my part!

**Comment by srdeaton** [comment] 2024-03-08 18:51
I was about to check that, but saw your post. Cool, was looking for something like method = 'lv' to get Levenshtein edit distance. I can see not changing anything, though it's not the definition, either seems people need to use transpositions or it does not cause enough of an issue for them to notice.  Except in my case, took a while to trace issues back to lev_distance(); transpositions incur more cost in general than substitutions, deletions, & insertions. For exceptions like genetics & spell-checkers, it's nice. Which, I think, are most of the applications.

**Comment by srdeaton** [comment] 2024-03-08 19:11
Sorry, should've clarified. The generality mentioned pertains to theoretical and applied together.
Thanks.
